[theme]
base = "dark"
primaryColor = "#7C3AED"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
